name: Contracts Testing

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      working-directory: contracts

    container:
      image: node:16

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test